# Generated by Django 5.2.7 on 2025-10-26 15:19

from django.db import migrations

# DỮ LIỆU BÀI TẬP CỐT LÕI (25 BÀI)
EXERCISE_LIST = [
    # --- 1. Squat (Ngồi xổm) ---
    {
        "name": "Barbell Back Squat",
        "description": "Gánh tạ đòn sau lưng, thực hiện động tác squat.",
        "video_url": "https://www.youtube.com/watch?v=Uv_GwnaE_S4",
        "muscle_group": "legs", "difficulty": "intermediate",
        "equipment": "full_gym", "movement_pattern": "squat"
    },
    {
        "name": "Bodyweight Squat",
        "description": "Đứng lên ngồi xuống không dùng tạ.",
        "video_url": "https://www.youtube.com/watch?v=C_VtOYc6j5c",
        "muscle_group": "legs", "difficulty": "beginner",
        "equipment": "bodyweight", "movement_pattern": "squat"
    },
    {
        "name": "Dumbbell Goblet Squat",
        "description": "Giữ 1 tạ đơn trước ngực và squat.",
        "video_url": "https://www.youtube.com/watch?v=2-V1D6b8r_0",
        "muscle_group": "legs", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "squat"
    },
    # --- 2. Hinge (Gập-Duỗi Hông) ---
    {
        "name": "Barbell Deadlift",
        "description": "Nâng tạ đòn từ mặt đất lên, giữ lưng thẳng.",
        "video_url": "https://www.youtube.com/watch?v=VL5Ab0T07e4",
        "muscle_group": "back", "difficulty": "advanced",
        "equipment": "full_gym", "movement_pattern": "hinge"
    },
    {
        "name": "Dumbbell Romanian Deadlift (RDL)",
        "description": "Giữ tạ đơn, gập hông và giữ gối hơi cong, tập trung vào đùi sau.",
        "video_url": "https://www.youtube.com/watch?v=Jb1zW2_y-8o",
        "muscle_group": "legs", "difficulty": "intermediate",
        "equipment": "basic_gym", "movement_pattern": "hinge"
    },
    {
        "name": "Bodyweight Glute Bridge",
        "description": "Nằm ngửa, co chân và đẩy hông lên cao, siết mông.",
        "video_url": "https://www.youtube.com/watch?v=wPM8d5Qe_bI",
        "muscle_group": "legs", "difficulty": "beginner",
        "equipment": "bodyweight", "movement_pattern": "hinge"
    },
    # --- 3. Horizontal Push (Đẩy ngang) ---
    {
        "name": "Barbell Bench Press",
        "description": "Nằm trên ghế, đẩy tạ đòn từ ngực lên.",
        "video_url": "https://www.youtube.com/watch?v=gRVjAtPip0Y",
        "muscle_group": "chest", "difficulty": "intermediate",
        "equipment": "full_gym", "movement_pattern": "horizontal_push"
    },
    {
        "name": "Dumbbell Bench Press",
        "description": "Nằm trên ghế, đẩy tạ đơn từ ngực lên.",
        "video_url": "https://www.youtube.com/watch?v=VMEMd63t90o",
        "muscle_group": "chest", "difficulty": "intermediate",
        "equipment": "basic_gym", "movement_pattern": "horizontal_push"
    },
    {
        "name": "Push Up",
        "description": "Chống đẩy.",
        "video_url": "https://www.youtube.com/watch?v=P7-qgD-93I4",
        "muscle_group": "chest", "difficulty": "beginner",
        "equipment": "bodyweight", "movement_pattern": "horizontal_push"
    },
    # --- 4. Horizontal Pull (Kéo ngang) ---
    {
        "name": "Dumbbell Row",
        "description": "Tựa 1 tay 1 gối lên ghế, kéo tạ đơn dọc sườn.",
        "video_url": "https://www.youtube.com/watch?v=Fglp2f_aWso",
        "muscle_group": "back", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "horizontal_pull"
    },
    {
        "name": "Barbell Bent-Over Row",
        "description": "Cúi người song song mặt đất, kéo tạ đòn vào bụng.",
        "video_url": "https://www.youtube.com/watch?v=Zl-8_Fp1_Lg",
        "muscle_group": "back", "difficulty": "intermediate",
        "equipment": "full_gym", "movement_pattern": "horizontal_pull"
    },
    # --- 5. Vertical Push (Đẩy dọc) ---
    {
        "name": "Dumbbell Overhead Press (Shoulder Press)",
        "description": "Ngồi hoặc đứng, đẩy tạ đơn qua đầu.",
        "video_url": "https://www.youtube.com/watch?v=qEwKCR5-j_Q",
        "muscle_group": "shoulders", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "vertical_push"
    },
    {
        "name": "Barbell Overhead Press (OHP)",
        "description": "Đứng, đẩy tạ đòn từ vai qua đầu.",
        "video_url": "https://www.youtube.com/watch?v=F3-60g_t4vE",
        "muscle_group": "shoulders", "difficulty": "intermediate",
        "equipment": "full_gym", "movement_pattern": "vertical_push"
    },
    {
        "name": "Pike Push Up",
        "description": "Chống đẩy với hông đẩy cao (biến thể của bodyweight).",
        "video_url": "https://www.youtube.com/watch?v=3-1_tDYfXMk",
        "muscle_group": "shoulders", "difficulty": "intermediate",
        "equipment": "bodyweight", "movement_pattern": "vertical_push"
    },
    # --- 6. Vertical Pull (Kéo dọc) ---
    {
        "name": "Pull Up",
        "description": "Hít xà đơn, kéo người lên.",
        "video_url": "https://www.youtube.com/watch?v=poyr8KenUfc",
        "muscle_group": "back", "difficulty": "intermediate",
        "equipment": "basic_gym", "movement_pattern": "vertical_pull"
    },
    {
        "name": "Lat Pulldown",
        "description": "Ngồi trên máy, kéo thanh tạ từ trên cao xuống ngực.",
        "video_url": "https://www.youtube.com/watch?v=0oe-m1m2-1k",
        "muscle_group": "back", "difficulty": "beginner",
        "equipment": "full_gym", "movement_pattern": "vertical_pull"
    },
    # --- 7. Lunge (Bước) ---
    {
        "name": "Dumbbell Lunge",
        "description": "Cầm tạ đơn, bước chân tới trước và hạ gối.",
        "video_url": "https://www.youtube.com/watch?v=D7KaQPHYgDA",
        "muscle_group": "legs", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "lunge"
    },
    {
        "name": "Bodyweight Lunge",
        "description": "Không cầm tạ, bước chân tới trước và hạ gối.",
        "video_url": "https://www.youtube.com/watch?v=QF0-f-f3p14",
        "muscle_group": "legs", "difficulty": "beginner",
        "equipment": "bodyweight", "movement_pattern": "lunge"
    },
    # --- 8. Core (Bụng/Lưng dưới) ---
    {
        "name": "Plank",
        "description": "Giữ tư thế tấm ván, siết chặt cơ bụng.",
        "video_url": "https://www.youtube.com/watch?v=B296mZDhrP4",
        "muscle_group": "core", "difficulty": "beginner",
        "equipment": "bodyweight", "movement_pattern": "core"
    },
    {
        "name": "Crunch",
        "description": "Nằm ngửa, gập bụng.",
        "video_url": "https://www.youtube.com/watch?v=Xyd_fa5zoEU",
        "muscle_group": "core", "difficulty": "beginner",
        "equipment": "bodyweight", "movement_pattern": "core"
    },
    {
        "name": "Hanging Knee Raise",
        "description": "Treo người trên xà và co gối lên bụng.",
        "video_url": "https://www.youtube.com/watch?v=Nggo3-83qco",
        "muscle_group": "core", "difficulty": "intermediate",
        "equipment": "basic_gym", "movement_pattern": "core"
    },
    # --- 9. Isolation (Bài tập đơn khớp) ---
    {
        "name": "Dumbbell Bicep Curl",
        "description": "Đứng hoặc ngồi, gập tay trước (cuốn tạ đơn).",
        "video_url": "https://www.youtube.com/watch?v=JbS-QkaErA0",
        "muscle_group": "arms", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "isolation"
    },
    {
        "name": "Tricep Dips (on bench)",
        "description": "Chống tay sau lên ghế và hạ người.",
        "video_url": "https://www.youtube.com/watch?v=B0v-GEJm-A4",
        "muscle_group": "arms", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "isolation"
    },
    {
        "name": "Leg Extension",
        "description": "Ngồi trên máy, duỗi (đá) chân.",
        "video_url": "https://www.youtube.com/watch?v=YyvSfVjSzuE",
        "muscle_group": "legs", "difficulty": "beginner",
        "equipment": "full_gym", "movement_pattern": "isolation"
    },
    {
        "name": "Dumbbell Lateral Raise",
        "description": "Đứng, nâng tạ đơn sang hai bên (tập vai ngang).",
        "video_url": "https://www.youtube.com/watch?v=WJm9zA2NY8E",
        "muscle_group": "shoulders", "difficulty": "beginner",
        "equipment": "basic_gym", "movement_pattern": "isolation"
    },
]

def seed_data(apps, schema_editor):
    """
    Gieo mầm dữ liệu bài tập vào CSDL.
    """
    Exercise = apps.get_model('api', 'Exercise')
    
    for item in EXERCISE_LIST:
        # Dùng get_or_create để tránh tạo trùng lặp nếu chạy lại migration
        # 'name' được giả định là unique
        Exercise.objects.get_or_create(name=item["name"], defaults=item)

def reverse_seed_data(apps, schema_editor):
    """
    Xóa dữ liệu đã gieo mầm nếu migration bị rollback.
    """
    Exercise = apps.get_model('api', 'Exercise')
    Exercise.objects.filter(name__in=[item["name"] for item in EXERCISE_LIST]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_equipment_exercise_movement_pattern_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_code=reverse_seed_data),
    ]
