# Generated by Django 5.2.7 on 2025-10-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_equipment_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='equipment_available',
            field=models.CharField(blank=True, choices=[('bodyweight', 'Chỉ tập Bodyweight'), ('basic_gym', 'Cơ bản (Tạ đơn, xà)'), ('full_gym', 'Phòng gym đầy đủ')], max_length=20, null=True),
        ),
    ]
