# Generated by Django 5.2.7 on 2025-10-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_equipment_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planexercise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='planexercise',
            unique_together={('plan', 'exercise', 'day_number')},
        ),
    ]
